In [1]:
import numpy as np

In [2]:
arr=np.array([[2,3,56,7],[2,6,8,9]],np.int8)

In [3]:
arr

array([[ 2,  3, 56,  7],
       [ 2,  6,  8,  9]], dtype=int8)

In [4]:
arr.shape

(2, 4)

In [5]:
arr[1,1]

6

In [6]:
arr.dtype


dtype('int8')

In [7]:
arr[1,3]=45

In [8]:
arr

array([[ 2,  3, 56,  7],
       [ 2,  6,  8, 45]], dtype=int8)

**ARRAY CREATION: CONVERSION FROM OTHER PYTHON STRUCTURES**

In [9]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

In [14]:
np.array({1,2,5})

array({1, 2, 5}, dtype=object)

In [15]:
zero=np.zeros((2,5))

In [16]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zero.dtype

dtype('float64')

In [18]:
zero.shape

(2, 5)

In [19]:
zero.size

10

In [20]:
rng=np.arange(15)

In [21]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
lspace=np.linspace(1,5,3)

In [23]:
lspace

array([1., 3., 5.])

In [24]:
lspace1=np.linspace(1,2,7)

In [25]:
lspace1

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        ])

In [26]:
emp=np.empty((2,6))

In [27]:
emp

array([[1.22417680e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000, 8.01097888e-307, 4.15996728e-061],
       [1.70391437e+160, 2.36053795e+180, 1.95375270e+184,
        5.15835364e-062, 1.77667452e+160, 3.30474032e+179]])

In [28]:
emp_like=np.empty_like(lspace1)

In [29]:
emp_like

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        ])

In [30]:
id=np.identity(3)

In [31]:
id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
id.shape

(3, 3)

In [33]:
arr=np.arange(99)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
arr=arr.reshape(3,33)

In [38]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [39]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
arr=arr.ravel()

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
arr.shape

(99,)

In [43]:
arr.size

99

In [44]:
x=[[1,2,3],[3,4,5],[6,7,9]]

In [45]:
x

[[1, 2, 3], [3, 4, 5], [6, 7, 9]]

In [46]:
my_arr=np.array(x)

In [47]:
my_arr

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 9]])

In [48]:
my_arr.sum(axis=0)

array([10, 13, 17])

In [49]:
my_arr.sum(axis=1)

array([ 6, 12, 22])

In [50]:
my_arr.T

array([[1, 3, 6],
       [2, 4, 7],
       [3, 5, 9]])

In [51]:
my_arr.flat

In [52]:
for item in my_arr.flat:
    print(item)

1
2
3
3
4
5
6
7
9


In [53]:
my_arr.ndim

2

In [54]:
my_arr.size

9

In [55]:
my_arr.shape

(3, 3)

In [56]:
my_arr.nbytes

36

In [57]:
one=np.array([[1,3,5,9,676,2]])

In [58]:
one

array([[  1,   3,   5,   9, 676,   2]])

In [59]:
one.argmax()

4

In [60]:
one.argmin()

0

In [61]:
one.argsort()

array([[0, 5, 1, 2, 3, 4]], dtype=int64)

In [62]:
my_arr

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 9]])

In [63]:
my_arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [64]:
my_arr.argmin()

0

In [65]:
my_arr.argmax()

8

In [66]:
my_arr.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [67]:
my_arr.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [68]:
my_arr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [69]:
my_arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [70]:
my_arr.ravel()

array([1, 2, 3, 3, 4, 5, 6, 7, 9])

In [71]:
my_arr.reshape((1,9))

array([[1, 2, 3, 3, 4, 5, 6, 7, 9]])

In [72]:
my_arr

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 9]])

In [73]:
my_arr2=np.array([[1,3,6],[2,6,9],[3,6,8]])

In [74]:
my_arr2

array([[1, 3, 6],
       [2, 6, 9],
       [3, 6, 8]])

In [75]:
ar=my_arr+my_arr2

In [76]:
ar

array([[ 2,  5,  9],
       [ 5, 10, 14],
       [ 9, 13, 17]])

In [77]:
my_arr*my_arr2

array([[ 1,  6, 18],
       [ 6, 24, 45],
       [18, 42, 72]])

In [78]:
np.sqrt(my_arr)

array([[1.        , 1.41421356, 1.73205081],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 3.        ]])

In [79]:
my_arr.sum()

40

In [80]:
my_arr.max()

9

In [81]:
my_arr.min()

1

In [82]:
np.where(my_arr>6)

(array([2, 2], dtype=int64), array([1, 2], dtype=int64))

In [83]:
my_arr.ndim

2

In [84]:
my_arr

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 9]])

In [85]:
np.count_nonzero(my_arr)

9

In [86]:
np.nonzero(my_arr)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [87]:
import sys

In [88]:
py_ar=[2,4,6,8,10]

In [89]:
np_ar=np.array(py_ar)

In [90]:
sys.getsizeof(1)*len(py_ar)

140

In [91]:
np_ar.itemsize*np_ar.size

20

In [92]:
np_ar.tolist()

[2, 4, 6, 8, 10]